log_dir: ./log/

retrieve_model:
  model_name_or_path: "bm25"
  batch_size: 256
  pooling: cls
  l2_norm: True
  k: 100
  device: cuda:0
  threads: 32
  ef_search:

reranker:
  model_name_or_path: 
  batch_size: 64
  cutoff_layers: 28
  device: 0

corpus:
  language: zn
  index_dir: ./indexes/Insurance/bm25_index/QA_index
  corpus_path: 

query:
  max_length: 256
  prefix:
  query_to_pos_path: